version: '3.8'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped
